(dp1
S'output'
p2
S'<class \'_mysql_exceptions.OperationalError\'> (1054, "Unknown column \'None\' in \'where clause\'")'
p3
sS'layer'
p4
S'D:\\web2py\\applications\\BrainChaco\\controllers/PreguntasController.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n# intente algo como\ndef index():\n   \tresponse.view=\'PreguntasController/index.html\'\n   \tpreguntas=[]\n   \trespuesta=[]\n   \treturn dict(preguntas=preguntas,respuesta=respuesta)\n\t\ndef seleccionar_pregunta():\n\tpreguntas = db.executesql(\'SELECT id,descripcion FROM pregunta WHERE idcat=\'+request.args(0)+\' ORDER BY RAND() LIMIT 1\')\n \tfor pregunta in preguntas:\n \t\tidPreg=str(pregunta[0])\n \trespuesta=db.executesql(\'SELECT descripcion FROM RESPUESTAPREGUNTA WHERE idPreg=\'+idPreg)\n \tresponse.view=\'PreguntasController/index.html\'\n \treturn dict(preguntas=preguntas,respuesta=respuesta)\n\ndef verificar_respuesta():\n\tresp_usuario= str(request.args(0))\n\tpreguntas=[]\n   \trespuesta=[]\n   \topcion=db.executesql(\'SELECT opcion from respuestapregunta WHERE descripcion=\'+resp_usuario)\n   \tfor resp in opcion():\n\t\tif str(resp[0])==\'V\':\n\t\t\tresponse.flash="RESPUESTA CORRECTA"\n\t\telse:\n\t\t\tresponse.flash="RESPUESTA INCORRECTA"\n\tresponse.view=\'PreguntasController/index.html\'\n \treturn dict(preguntas=preguntas,respuesta=respuesta)\nresponse._vars=response._caller(verificar_respuesta)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "D:\\web2py\\gluon\\restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "D:\\web2py\\applications\\BrainChaco\\controllers/PreguntasController.py", line 29, in <module>\n  File "D:\\web2py\\gluon\\globals.py", line 417, in <lambda>\n    self._caller = lambda f: f()\n  File "D:\\web2py\\applications\\BrainChaco\\controllers/PreguntasController.py", line 21, in verificar_respuesta\n    opcion=db.executesql(\'SELECT opcion from respuestapregunta WHERE descripcion=\'+resp_usuario)\n  File "D:\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 1019, in executesql\n    adapter.execute(query)\n  File "D:\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\base.py", line 1388, in execute\n    return self.log_execute(*a, **b)\n  File "D:\\web2py\\gluon\\packages\\dal\\pydal\\adapters\\base.py", line 1382, in log_execute\n    ret = self.get_cursor().execute(command, *a[1:], **b)\n  File "MySQLdb/cursors.py", line 205, in execute\n  File "MySQLdb/connections.py", line 36, in defaulterrorhandler\nOperationalError: (1054, "Unknown column \'None\' in \'where clause\'")\n'
p11
s.